### ISSUE TITLE
Pushing to S3 failed: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

### ISSUE THREAD

**Issue by uhofemeier** [aws-samples/aws-deeplens-worker-safety-project#2]
I followed the instructions provided and am seeing an error message in the AWS IoT Console after deploying the project. 

Pushing to S3 failed: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

Help please :)

Thanks.
Ulf

**Comment by verhagenkava** [comment]
I'm currently having the same issue.

Did you manage to solve it?

Thanks, Kava.

**Comment by uhofemeier** [comment]
I have not.

**Comment by paulbright** [comment]
from [https://forums.aws.amazon.com/thread.jspa?threadID=287187](https://forums.aws.amazon.com/thread.jspa?threadID=287187)

Create policy
1. go to IAM console https://console.aws.amazon.com/iam/home?region=us-east-1
2. on the left panel, click on "policies", then click "create policy"
3. on the next page, click on "choose a service", then choose "s3"
4. for "actions", you can pick "list", "read" and "write" for now, you can revise the permission later.
5. for "resources", you can specify bucket and object by providing the ARNs, or choose "all resources" to allow access to all your s3 resources
6. you don't need to specify "request conditions"
7. click "review policy" to go to the next page
8. review policy and choose a name for the policy, then click "create policy"
9. go back to IAM console, click on "roles", you should see "AWSDeepLensGreengrassGroupRole"
10. click on that role, then click on "attach policy", choose the policy you just created.

You can find more information about IAM policy here: https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_create.html


and my code is

```
import boto3
from botocore.session import Session

def write_image_to_s3(cv2frame):
    session = Session()
    creds = session.get_credentials()
    s3 = session.create_client('s3',
        aws_access_key_id=creds.access_key, 
        aws_secret_access_key=creds.secret_key,
        aws_session_token=creds.token)

    file_name = 'xyz.jpg'
    encode_param=[int(cv2.IMWRITE_JPEG_QUALITY),90]
    _, jpg_data = cv2.imencode('.jpg', cv2frame, encode_param)
    response = s3.put_object(Bucket="yourbucketname", Body=jpg_data.tostring(),Key=file_name)

```
