### ISSUE TITLE
Issue with Worker-safety project for Public Access

### ISSUE THREAD

**Issue by SrinivasMadsi** [aws-samples/aws-deeplens-worker-safety-project#3]
Hi Team, I have deployed worker-safety model in deeplens as instructed. While performing the instructions I have made S3 bucket as public and I have enabled 'Un authenticated' access in "Cognito" tab due to this it is coming under compliance issue and I  got stuck to resolve it. Could you please provide me instructions to resolve my S3 bucket and "un authenticated" access issues without disturbing my project.

**Comment by darwaishx** [comment]
It has been updated to use S3 presigned urls so objects dont need to be public anymore.
